[project]
name = 'sbtc-liquidity-router'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cross-chain]
path = 'contracts/cross-chain.clar'
clarity_version = 3
epoch = 'latest'

[contracts.liquidity-router]
path = 'contracts/liquidity-router.clar'
clarity_version = 3
epoch = '3.1'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
